name: microdiff
description: Microdiff is fast, zery dependency object and array comparison library.
version: 1.0.0
repository: https://github.com/avesbox/microdiff
homepage: https://github.com/avesbox/microdiff
topics:
  - comparison
  - differences

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^4.0.0
  test: ^1.24.0
